/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 17:49:13 GMT 2020
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Foo;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Foo_ESTest extends Foo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Foo foo0 = new Foo();
      boolean boolean0 = foo0.isFoo();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Foo foo0 = new Foo();
      boolean boolean0 = foo0.testMe(44);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Foo foo0 = new Foo();
      foo0.inc();
      assertFalse(foo0.isFoo());
      
      foo0.inc();
      boolean boolean0 = foo0.isFoo();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Foo foo0 = new Foo();
      boolean boolean0 = foo0.testMe(42);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Foo foo0 = new Foo();
      boolean boolean0 = foo0.testMe((-2441));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Foo foo0 = new Foo();
      foo0.inc();
      foo0.inc();
      assertTrue(foo0.isFoo());
      
      foo0.inc();
      boolean boolean0 = foo0.isFoo();
      assertFalse(boolean0);
  }
}
