/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 01 17:59:02 GMT 2020
 */

package org.example;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Foo_ESTest_scaffolding;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Foo_ESTest_scaffolding_ESTest extends Foo_ESTest_scaffolding_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Foo_ESTest_scaffolding.setSystemProperties();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Foo_ESTest_scaffolding foo_ESTest_scaffolding0 = new Foo_ESTest_scaffolding();
  }
}
